name: PR Validation

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]

jobs:
    pr-validation:
        uses: ./.github/workflows/reusable-pr-validation.yml
        permissions:
            contents: read
            pull-requests: write
    conventional-commits:
        uses: ./.github/workflows/reusable-conventional-commits.yml
