name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        uses: ./.github/workflows/reusable-release.yml
        permissions:
            contents: write
            pull-requests: write
    conventional-commits:
        uses: ./.github/workflows/reusable-conventional-commits.yml
