name: Stale

on:
    schedule:
        - cron: '0 6 * * *'

jobs:
    stale:
        uses: ./.github/workflows/reusable-stale.yml
        permissions:
            issues: write
            pull-requests: write
